---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 1232226721920737280-oKWq1sI7NuRi10QUrWvGnI9SiiGrlC
:access_token_secret: s27Xz2mTx2swFBcpT9GPshm8WJdBWCunOwYKhTauecV7K
